#!/usr/bin/perl -w

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: cleanLogs
#
# !DESCRIPTION: This Perl script removes all individual log files from
#  GEOS-FP data processing jobs from the log directory.
#\\
#\\
# !USES:
#
  require 5.003;        # Need this version of Perl or newer
  use strict;           # Force IMPLICIT NONE-style declarations
#
# !PUBLIC MEMBER FUNCTIONS:
#
# getDefaults($$)
# &main         
#
# !CALLING SEQUENCE:
#  cleanLogs
#
# !REVISION HISTORY: 
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS-5/perl/cleanLogs
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getDefaults
#
# !DESCRIPTION: Routine getDefaults reads the input file and returns the
#  name of the directory where log files are stored.
#\\
#\\
# !INTERFACE:
#
sub getDefaults($) {
#
# !INPUT PARAMETERS:
#
  # $fileName : File containing default settings to be read
  my ( $fileName ) = @_;
#
# !RETURN VALUE:
#
  my $logDir  = "";  # Directory where log files are found
#
# !CALLING SEQUENCE:
#  $logDir = &getDefaults( $fileName );
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS-5/perl/cleanLogs
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my @file    = "";
 
  # Read data from input file
  open( I, "<$fileName" ) or die "Cannot open $fileName!\n";
  chomp( @file = <I> );
  close( I );

  # Parse each line until we find the log directory
  for ( my $i = 0; $i < scalar( @file ); $i++ ) {
    if ( $file[$i] =~ "==> Log Directory" ) { $logDir = $file[++$i]; }
  }

  # Return to main program
  return( $logDir );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: main
#
# !DESCRIPTION: Main is the driver program fxor the cleanLogs script.
#\\
#\\
# !INTERFACE:
#
sub main() {
#
# !CALLING SEQUENCE:
#  &main();
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS-5/perl/cleanLogs
#  20 Sep 2013 - R. Yantosca - Now reads input file "doGeosFp.input"

#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my $cmd    = "";
  my $file   = "";
  my @files  = ();
  my $logDir = &getDefaults( "doGeosFp.input" );
  
  # Read all log files in the directory
  opendir( D, "$logDir" ) or die "$logDir is an invalid directory!\n";
  chomp( @files = readdir( D ) );
  closedir( D );

  # Remove log files only
  foreach $file ( @files ) {
    if ( $file =~ m/log.doGeos5/ ) {
      $cmd = "rm -f $logDir/$file";
      print "$cmd\n";
      qx( $cmd );
    } 
  }				

  # Return w/ status
  return( $? );
}
#EOC

#------------------------------------------------------------------------------

# Call main driver routine
main();

# Exit and pass status code to Unix shell
exit( $? );
