#!/usr/bin/perl -w

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: doGeosFpFixA3Cld
#
# !DESCRIPTION: This Perl script is the driver script for Geos5Driver, the
#  Fortran code for processing GEOS-FP met field data.  This script
#  submits several executables in separate threads to achieve coarse-grain
#  parallelization.
#\\
#\\
# !USES:
#
  require 5.003;        # need this version of Perl or newer
  use strict;           # Do not allow symbolic references
#
# !PUBLIC MEMBER FUNCTIONS:
#
# getDefaults($$)
# getSysVars()
# checkInputs()
# replaceTokens($)
# checkDir($)
# main()
#
# !PUBLIC DATA MEMBERS:
#
  #============================================================
  # Define global variables (seen in all subroutines below)
  #============================================================
  our $CODE_DIRECTORY    = "";
  our $DATE_FILE         = "";
  our $DATE_STRING       = "";
  our $DAY_STRING        = "";
  our $EMAIL_STRING      = "";
  our $EXECUTABLE        = "";
  our $HOME_DIRECTORY    = "";
  our $JOB_DIRECTORY     = "";
  our $JOB_FILE          = "";
  our $LOG_DIRECTORY     = "";
  our $LOG_ERR           = "";
  our $LOG_FILE          = "";
  our $MET_DIRECTORY     = "";
  our $MONTH_STRING      = "";
  our $N_FILES           = 16;
  our $SUBMIT            = "";
  our $TEMP_DIRECTORY    = "";
  our $USER_ID           = "";
  our $YEAR_STRING       = "";
#
# !CALLING SEQUENCE:
#  doGeosFpFixA3Cld YYYYMMDD
#
# !REMARKS:
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getDefaults
#
# !DESCRIPTION:  Routine getDefaults reads the default values for 
#  input quantities.
#\\
#\\
# !INTERFACE:
#
sub getDefaults($$) {
#
# !INPUT PARAMETERS:
#
  # $fileName : File containing default settings to be read
  # $date     : YYYYMMDD date for which to process met data
  my ( $fileName, $date ) = @_;
#
# !CALLING SEQUENCE:
# &getDefaults( FILENAME, DATE );
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#  07 Aug 2013 - R. Yantosca - Now also get value for $MET_DIRECTORY
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my $line = "";   
  my @file = "";

  #--------------------------------------
  # Read variable settings from the file
  #--------------------------------------

  # Read defaults file into an array (remove newlines)
  open( I, "<$fileName" ) or die "Cannot open $fileName!\n";
  chomp( @file = <I> );
  close( I );

  # Loop thru each line in the file
  for ( my $i = 0; $i < scalar( @file ); $i++ ) {

    if ( $file[$i] =~ "==> Submit Statement" ) {
      $SUBMIT = $file[++$i];
       
    } elsif ( $file[$i] =~ "==> Code Directory" ) {
      $CODE_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Job Directory" ) {
      $JOB_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Log Directory" ) {
      $LOG_DIRECTORY  = $file[++$i];

    } elsif ( $file[$i] =~ "==> Temporary Directory" ) {
      $TEMP_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Program Executable" ) {
      $EXECUTABLE = $file[++$i];

    } elsif ( $file[$i] =~ "==> Emails for Notification" ) {
      $EMAIL_STRING = $file[++$i];

    } elsif ( $file[$i] =~ "==> Raw Met Data Directory" ) {
      $MET_DIRECTORY = $file[++$i];
    }
  }

  #--------------------------------------
  # Define other variables
  #--------------------------------------

  # Date strings
  $DATE_STRING  = "$date";
  $YEAR_STRING  = substr( $date, 0, 4 );
  $MONTH_STRING = substr( $date, 4, 2 );
  $DAY_STRING   = substr( $date, 6, 2 );

  # File to pass date to F90 code
  $DATE_FILE    = "$TEMP_DIRECTORY/$DATE_STRING.$$";

  # Log error file
  $LOG_ERR      = "$LOG_DIRECTORY/log.doGeosFpFixA3Cld.error";

  # Log file
  $LOG_FILE     = "$LOG_DIRECTORY/log.doGeosFpFixA3Cld.{DSTR}.$$";

  # Job script
  $JOB_FILE     = "$JOB_DIRECTORY/job.doGeosFpFixA3Cld.{DSTR}.$$";  

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getSysVars
#
# !DESCRIPTION: Routine getSysVars returns system variables \$USER and \$HOME.
#\\
#\\
# !INTERFACE:
#
sub getSysVars() {
#
# !CALLING SEQUENCE:
# &getSysVars();
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#BOC

  # User ID (remove newline)
  $USER_ID = qx( echo \$USER );
  chomp( $USER_ID );
  
  # Home directory (remove newline)
  $HOME_DIRECTORY = qx( echo \$HOME );
  chomp( $HOME_DIRECTORY );

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkInputs
#
# !DESCRIPTION: Routine checkInputs does the following:
# \begin{enumerate}
# \item Replaces string tokens in variables with replacement text
# \item Checks to see if directories exist
# \end{enumerate}
#
# !INTERFACE:
#
sub checkInputs() {
#
# !CALLING SEQUENCE:
# &checkInputs();
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#------------------------------------------------------------------------------
#BOC

  #---------------------------------
  # Script file & directory names
  #---------------------------------

  # Replace tokens
  $CODE_DIRECTORY    = &replaceTokens( $CODE_DIRECTORY );
  $JOB_DIRECTORY     = &replaceTokens( $JOB_DIRECTORY  );
  $JOB_FILE          = &replaceTokens( $JOB_FILE       );
  $LOG_DIRECTORY     = &replaceTokens( $LOG_DIRECTORY  );
  $LOG_ERR           = &replaceTokens( $LOG_ERR        );
  $LOG_FILE          = &replaceTokens( $LOG_FILE       );
  $SUBMIT            = &replaceTokens( $SUBMIT         );
  $TEMP_DIRECTORY    = &replaceTokens( $TEMP_DIRECTORY );

  # Check if directories exists
  &checkDir( $CODE_DIRECTORY );
  &checkDir( $JOB_DIRECTORY  );
  &checkDir( $LOG_DIRECTORY  );
  &checkDir( $TEMP_DIRECTORY );
  &checkDir( $MET_DIRECTORY  );

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: replaceTokens
#
# !DESCRIPTION: Subroutine replaceTokens replaces tokens in a variable.  
#\\
#\\
# !INTERFACE:
#
sub replaceTokens($) {
#
# !INPUT PARAMETERS:
#
  # $var: Name of the string in which to replace tokens
  my ( $var ) = @_; 
#
# !CALLING SEQUENCE:
#  $var = &replaceTokens( $var );
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#BOC

  # Replace tokens in the variable names
  $var =~ s/{DSTR}/$DATE_STRING/g;
  $var =~ s/{HOME}/$HOME_DIRECTORY/g;
  $var =~ s/{JOB}/$JOB_FILE/g;
  $var =~ s/{LOGERR}/$LOG_ERR/g;
  $var =~ s/{USER}/$USER_ID/g;
  $var =~ s/YYYY/$YEAR_STRING/g;
  $var =~ s/MM/$MONTH_STRING/g;
  $var =~ s/DD/$DAY_STRING/g;
 
  # Return to calling program
  return( $var );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkDir
#
# !DESCRIPTION: Subroutine checkDir checks to see if a directory exists.
#\\
#\\
# !INTERFACE:
#
sub checkDir($) {
#
# !INPUT PARAMETERS:
#
  # $dir : Directory to be checked
  my ( $dir ) = @_;
#
# !CALLING SEQUENCE:
#  &checkDir( $dir );
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#BOC

  # Stop with error if directory doesn't exist
  if ( !( -d $dir ) ) { 
    print "doGeosFpMulti: ERROR: Directory does not exist: $dir\n";
    exit(1)
  }
  
  # Otherwise return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: makeJobFile
#
# !DESCRIPTION: Subroutine makeJobFile creates a job script that calls
#  the executable to reprocess the GEOS-FP A3cld data.
#\\
#\\
# !INTERFACE:
#
sub makeJobFile {
#
# !CALLING SEQUENCE:
#  &makeJobFile   # Runs executable GeosFpDriver0.x
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # Create shadow variables
  my $body      = "File types A3cld are now created for $DATE_STRING. ";
     $body     .= "Files shall be visible on /mnt/gcgrid within 15 minutes.";
  my $email     = $EMAIL_STRING;
  my $exeFile   = "GeosFpFixA3Cld.x";
  my $jobFile   = $JOB_FILE;
  my $logFile   = $LOG_FILE;
  my $subject   = "GEOS-FP A3cld met fields for $DATE_STRING are ready!";
  my $mailCmd   = qq( echo "$body" > X | mail -s "$subject" $email < X; rm -f X );

  #-----------------------------------------
  # Create a file with the date of the data
  #-----------------------------------------

  # Save date in a file to pass to the F90 code
  open( O, ">$DATE_FILE" ) or die "Cannot open $DATE_FILE!\n";
  print O "$DATE_STRING\n";
  close( O );

  #-----------------------------------------
  # Define job script in a "here" document
  #-----------------------------------------

  # Create HERE document
  my $txt =<<EOF;
#!/usr/bin/perl -w

# Local variables
my \$sLog  = qq($logFile);

# Make files world-readable
umask(022);

# Echo starting time
qx( echo "==============================================" >> \$sLog );
qx( echo "doGeosFpFixA3Cld: Extracting GEOS-FP Met Data!" >> \$sLog );
qx( echo "Started on `date`"                              >> \$sLog );
qx( echo                                                  >> \$sLog );

# List the temp directory first to force a directory mount
qx( ls $TEMP_DIRECTORY > /dev/null );

# Run the GEOS-5 data extraction code
qx( umask 022; cd $CODE_DIRECTORY; $exeFile < $DATE_FILE >> \$sLog );

# Move files from the temp directory to the data directory
qx( ./moveGeosFp $DATE_STRING A3cld >> \$sLog );

# Send an email that the job is finished
if ( \$\? == 0 ) { qx( $mailCmd ); }

# Remove the date file
qx( rm -f $DATE_FILE >> /dev/null ); 

# Echo ending time
qx( echo                      >> \$sLog );
qx( echo "Finished on `date`" >> \$sLog );
qx( echo                      >> \$sLog );

exit(0);
EOF

  # Write job script to a file
  open( O, ">$jobFile" ) or die "Cannot open $jobFile\n";
  print O "$txt\n";
  close( O );

  # Make run script executable
  chmod( 0755, $jobFile );

  # Return normally
  return( 0 );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: runJobs
#
# !DESCRIPTION: Subroutine runJob executes 3 job scripts simultaneiously,
#  each in a different Unix process.
#\\
#\\
# !INTERFACE:
#
sub runJobs() {
#
# !CALLING SEQUENCE:
#  &runJobs();     # Submits all job scripts simultaneously
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my @threads  = ( 0 .. 2 );
  my @job      = qw( a b c );

  # Command to run all jobs in the background
  # NOTE: We need to use a TCSH script to get jobs to submit in parallel
  my $cmd = "./runMet job";

  # Submit all jobs in multiple threads
  qx( $cmd );

  # Return normally
  return( 0 );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: main
#
# !DESCRIPTION: Routine main is the driver routine for the doGeos5 script.
#\\
#\\
# !INTERFACE:
#
sub main() {
#
# !CALLING SEQUENCE:
#  &main();
#
# !REVISION HISTORY:
#  05 Dec 2013 - R. Yantosca - Initial version, based on doGeosFpMulti
#EOP
#------------------------------------------------------------------------------
#
# !LOCAL VARIABLES:
#
  # Scalars
  my $status  = 0;
  my $listCmd = "";
  my $cmd     = "";
  my $file    = "";

  # Arrays
  my @files   = ();

  # Error check arguments
  if ( scalar( @ARGV ) == 0 ) { 
    print "Usage: doGeosFpFixA3Cld YYYYMMDD\n"; 
    exit(1);
  }

  # Get default values
  &getDefaults( "doGeosFp.input", $ARGV[0] );

  # Quick & dirty test if all the files are present in the met dir
  # Not an exhaustive check but this should be good enough to prevent the
  # met field code from starting if there aren't enough files. (bmy, 8/7/13)
  $listCmd = "ls -1 $MET_DIRECTORY/GEOS.fp*"."@ARGV"."*";
  chomp( @files = qx( $listCmd ) );

  # Check for 16 tavg3_3d_cld_Nv + tavg3_3d_rad_Nv files
  foreach $file ( @files ) {
    if ( ( $file =~ m/tavg3_3d_cld_Nv/ ) || 
         ( $file =~ m/tavg3_3d_rad_Nv/ )    ) { $status++; }
  }

  # Make sure we match the expected # of files
  if ( $status == $N_FILES ) { 
    print "doGeosFpMulti: All files present!  Now processing met for $ARGV[0]!\n"; 
  } else {
    print "doGeosFpMulti: Not enough raw met files for $ARGV[0]!\n"; 
    exit(1); 
  }

  # Get system variables
  &getSysVars();

  # Replace tokens w/ values and error check directories
  &checkInputs();

  # Write the job file and submit it to the queue
  &makeJobFile();

  # run the job
  qx( $JOB_FILE );

  # Return normally
  return(0);
}
#EOC

#------------------------------------------------------------------------------

# Start main program
main();

# Exit normally
exit(0);
