#!/usr/bin/perl -w

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: doGeos57Multi
#
# !DESCRIPTION: This Perl script is the driver script for Geos5Driver, the
#  Fortran code for processing GEOS-5.7.x met field data.  This script
#  submits several executables in separate threads to achieve coarse-grain
#  parallelization.
#\\
#\\
# !USES:
#
  require 5.003;        # need this version of Perl or newer
  use strict 'refs';    # Do not allow symbolic references
  use strict 'subs';    # Treat all barewords as syntax errors 
#
# !PUBLIC MEMBER FUNCTIONS:
#
# getDefaults($$)
# getSysVars()
# checkInputs()
# replaceTokens($)
# checkDir($)
# runJob($)
# main()
#
# !PUBLIC DATA MEMBERS:
#
  #============================================================
  # Define global variables (seen in all subroutines below)
  #============================================================
  $CODE_DIRECTORY    = "UNDEFINED";
  $DATE_FILE         = "UNDEFINED";
  $DATE_STRING       = "UNDEFINED";
  $DAY_STRING        = "UNDEFINED";
  $EXECUTABLE        = "UNDEFINED";
  $HOME_DIRECTORY    = "UNDEFINED";
  $JOB_DIRECTORY     = "UNDEFINED";
  $JOB_FILE          = "UNDEFINED";
  $LOG_DIRECTORY     = "UNDEFINED";
  $LOG_ERR           = "UNDEFINED";
  $LOG_FILE          = "UNDEFINED";
  $MONTH_STRING      = "UNDEFINED";
  $SUBMIT            = "UNDEFINED";
  $TEMP_DIRECTORY    = "UNDEFINED";
  $USER_ID           = "UNDEFINED";
  $YEAR_STRING       = "UNDEFINED";
#
# !CALLING SEQUENCE:
# doGeos57 YYYYMMDD
#
# !REVISION HISTORY: 
#  20 Jan 2012 - R. Yantosca - Initial version
#  23 Jan 2012 - R. Yantosca - Modified to submit processes on 3 threads
#                              simultaneously
#  16 Feb 2012 - R. Yantosca - Removed routine getDirectories and related
#                              variables; these are now in moveGeos57
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getDefaults
#
# !DESCRIPTION:  Routine getDefaults reads the default values for 
#  input quantities.
#\\
#\\
# !INTERFACE:
#
sub getDefaults($$) {
#
# !INPUT PARAMETERS:
#
  # $fileName : File containing default settings to be read
  # $date     : YYYYMMDD date for which to process met data
  my ( $fileName, $date ) = @_;
#
# !CALLING SEQUENCE:
# &getDefaults( FILENAME, DATE );
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my $line = "";   
  my @file = "";

  #--------------------------------------
  # Read variable settings from the file
  #--------------------------------------

  # Read defaults file into an array (remove newlines)
  open( I, "<$fileName" ) or die "Cannot open $fileName!\n";
  chomp( @file = <I> );
  close( I );

  # Loop thru each line in the file
  for ( my $i = 0; $i < scalar( @file ); $i++ ) {

    if ( $file[$i] =~ "==> Submit Statement" ) {
      $SUBMIT = $file[++$i];
       
    } elsif ( $file[$i] =~ "==> Code Directory" ) {
      $CODE_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Job Directory" ) {
      $JOB_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Log Directory" ) {
      $LOG_DIRECTORY  = $file[++$i];

    } elsif ( $file[$i] =~ "==> Temporary Directory" ) {
      $TEMP_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Program Executable" ) {
      $EXECUTABLE = $file[++$i];

    }
  }

  #--------------------------------------
  # Define other variables
  #--------------------------------------

  # Date strings
  $DATE_STRING  = "$date";
  $YEAR_STRING  = substr( $date, 0, 4 );
  $MONTH_STRING = substr( $date, 4, 2 );
  $DAY_STRING   = substr( $date, 6, 2 );

  # File to pass date to F90 code
  $DATE_FILE    = "$TEMP_DIRECTORY/$DATE_STRING.$$";

  # Log error file
  $LOG_ERR      = "$LOG_DIRECTORY/log.doGeos57.error-{THREAD}";

  # Log file
  $LOG_FILE     = "$LOG_DIRECTORY/log.doGeos57.{DSTR}.$$-{THREAD}";

  # Job script
  $JOB_FILE     = "$JOB_DIRECTORY/job.doGeos57.{DSTR}.$$-{THREAD}";  

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getSysVars
#
# !DESCRIPTION: Routine getSysVars returns system variables \$USER and \$HOME.
#\\
#\\
# !INTERFACE:
#
sub getSysVars() {
#
# !CALLING SEQUENCE:
# &getSysVars();
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

  # User ID (remove newline)
  $USER_ID = qx( echo \$USER );
  chomp( $USER_ID );
  
  # Home directory (remove newline)
  $HOME_DIRECTORY = qx( echo \$HOME );
  chomp( $HOME_DIRECTORY );

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkInputs
#
# !DESCRIPTION: Routine checkInputs does the following:
# \begin{enumerate}
# \item Replaces string tokens in variables with replacement text
# \item Checks to see if directories exist
# \end{enumerate}
#
# !INTERFACE:
#
sub checkInputs() {
#
# !CALLING SEQUENCE:
# &checkInputs();
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

  #---------------------------------
  # Script file & directory names
  #---------------------------------

  # Replace tokens
  $CODE_DIRECTORY    = &replaceTokens( $CODE_DIRECTORY );
  $JOB_DIRECTORY     = &replaceTokens( $JOB_DIRECTORY  );
  $JOB_FILE          = &replaceTokens( $JOB_FILE       );
  $LOG_DIRECTORY     = &replaceTokens( $LOG_DIRECTORY  );
  $LOG_ERR           = &replaceTokens( $LOG_ERR        );
  $LOG_FILE          = &replaceTokens( $LOG_FILE       );
  $SUBMIT            = &replaceTokens( $SUBMIT         );
  $TEMP_DIRECTORY    = &replaceTokens( $TEMP_DIRECTORY );

  # Check if directories exists
  &checkDir( $CODE_DIRECTORY );
  &checkDir( $JOB_DIRECTORY  );
  &checkDir( $LOG_DIRECTORY  );
  &checkDir( $TEMP_DIRECTORY );

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: replaceTokens
#
# !DESCRIPTION: Subroutine replaceTokens replaces tokens in a variable.  
#\\
#\\
# !INTERFACE:
#
sub replaceTokens($) {
#
# !INPUT PARAMETERS:
#
  # $var: Name of the string in which to replace tokens
  my ( $var ) = @_; 
#
# !CALLING SEQUENCE:
#  $var = &replaceTokens( $var );
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

  # Replace tokens in the variable names
  $var =~ s/{DSTR}/$DATE_STRING/g;
  $var =~ s/{HOME}/$HOME_DIRECTORY/g;
  $var =~ s/{JOB}/$JOB_FILE/g;
  $var =~ s/{LOGERR}/$LOG_ERR/g;
  $var =~ s/{USER}/$USER_ID/g;
  $var =~ s/YYYY/$YEAR_STRING/g;
  $var =~ s/MM/$MONTH_STRING/g;
  $var =~ s/DD/$DAY_STRING/g;
 
  # Return to calling program
  return( $var );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkDir
#
# !DESCRIPTION: Subroutine checkDir checks to see if a directory exists.
#\\
#\\
# !INTERFACE:
#
sub checkDir($) {
#
# !INPUT PARAMETERS:
#
  # $dir : Directory to be checked
  my ( $dir ) = @_;
#
# !CALLING SEQUENCE:
#  &checkDir( $dir );
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

  # Stop with error if directory doesn't exist
  if ( !( -d $dir ) ) { 
    print "doGeos5 ERROR: Directory does not exist: $dir\n";
    exit(1)
  }
  
  # Otherwise return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: makeJobFile
#
# !DESCRIPTION: Subroutine makeJobFile creates a job script for each 
#  process.  The thread number (0,1,2) is appended to the script names and
#  log files.
#\\
#\\
# !INTERFACE:
#
sub makeJobFile($) {
#
#
# !INPUT PARAMETERS:
#
  my ( $thread ) = @_;   # Thread number 
#
# !CALLING SEQUENCE:
#  &runJob( 0 );   # Runs executable Geos57Driver0.x
#  &runJob( 1 );   # Runs executable Geos57Driver1.x, etc.
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # Create shadow variables
  my $exeFile   = $EXECUTABLE;
  my $jobFile   = $JOB_FILE;
  my $logFile   = $LOG_FILE;
  my $fileTypes = "";

  #-----------------------------------------
  # Create a file with the date of the data
  #-----------------------------------------

  # Save date in a file to pass to the F90 code
  open( O, ">$DATE_FILE" ) or die "Cannot open $DATE_FILE!\n";
  print O "$DATE_STRING\n";
  close( O );

  #-----------------------------------------
  # Define job script in a "here" document
  #-----------------------------------------

  # Replace tokens for thread number in local shadow variables
  $exeFile =~ s/{THREAD}/$thread/g;
  $jobFile =~ s/{THREAD}/$thread/g;
  $logFile =~ s/{THREAD}/$thread/g;

  # Pick the proper file types
  if    ( $thread == 0 ) { $fileTypes = "A1 I3";                      }
  elsif ( $thread == 1 ) { $fileTypes = "A3cld A3dyn";                }
  elsif ( $thread == 2 ) { $fileTypes = "A3mstC A3mstE";              }
  else                   { print "Invalid thread number!\n"; exit(1); }

  # Create HERE document
  my $txt =<<EOF;
#!/usr/bin/perl -w

# Local variables
my \$sLog  = qq($logFile);

# Make files world-readable
umask(022);

# Echo starting time
qx( echo "=======================================" >> \$sLog );
qx( echo "doGeos5: Extracting GEOS-5 Met Data!"    >> \$sLog );
qx( echo "Started on `date`"                       >> \$sLog );
qx( echo                                           >> \$sLog );

# Run the GEOS-5 data extraction code
qx( umask 022; cd $CODE_DIRECTORY; $exeFile < $DATE_FILE >> \$sLog );

# Move files from the temp directory to the data directory
qx( ./moveGeos57 $DATE_STRING $fileTypes >> \$sLog );

# Remove the date file
qx( rm -f $DATE_FILE >> /dev/null ); 

# Echo ending time
qx( echo                      >> \$sLog );
qx( echo "Finished on `date`" >> \$sLog );
qx( echo                      >> \$sLog );

exit(0);
EOF

  # Write job script to a file
  open( O, ">$jobFile" ) or die "Cannot open $jobFile\n";
  print O "$txt\n";
  close( O );

  # Make run script executable
  chmod( 0755, $jobFile );

  # Return normally
  return( 0 );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: runJobs
#
# !DESCRIPTION: Subroutine runJob executes 3 job scripts simultaneiously,
#  each in a different Unix process.
#\\
#\\
# !INTERFACE:
#
sub runJobs() {
#
# !CALLING SEQUENCE:
#  &runJobs();     # Submits all job scripts simultaneously
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my @threads  = ( 0 .. 2 );
  my @job      = qw( a b c );

  foreach ( my $i=0; $i<=2; $i++ ) {
    $job[$i] = $JOB_FILE;
    $job[$i] =~ s/{THREAD}/$threads[$i]/g; 
  }

  # Command to run all jobs in the background
  # NOTE: We need to use a TCSH script to get jobs to submit in parallel
  my $cmd = "./runMet $job[0] $job[1] $job[2]";

  # Submit all jobs in multiple threads
  qx( $cmd );

  # Return normally
  return( 0 );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: main
#
# !DESCRIPTION: Routine main is the driver routine for the doGeos5 script.
#\\
#\\
# !INTERFACE:
#
sub main() {
#
# !CALLING SEQUENCE:
#  &main();
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------

  # Error check arguments
  if ( scalar( @ARGV ) == 0 ) { 
    print "Usage: doGeos57Multi YYYYMMDD\n"; 
    exit(1);
  }

  # Get default values
  &getDefaults( "doGeos57.input", $ARGV[0] );

  # Get system variables
  &getSysVars();

  # Replace tokens w/ values and error check directories
  &checkInputs();

  # Write the job file and submit it to the queue
  &makeJobFile( 0 );   # Creates A1, I3, (and CN if necessary) files
  &makeJobFile( 1 );   # Creates A3cld and A3dyn files
  &makeJobFile( 2 );   # Creates A3mstC and A3mstE files

  # Run jobs
  &runJobs();

  # Return normally
  return(0);
}
#EOC

#------------------------------------------------------------------------------

# Start main program
main();

# Exit normally
exit(0);
