#!/usr/bin/perl -w

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: doGeos57
#
# !DESCRIPTION: This Perl script is the driver script for Geos5Driver, the
#  Fortran code for processing GEOS-5.7.x met field data.
#\\
#\\
# !USES:
#
  require 5.003;        # need this version of Perl or newer
  use strict 'refs';    # Do not allow symbolic references
  use strict 'subs';    # Treat all barewords as syntax errors 
#
# !PUBLIC MEMBER FUNCTIONS:
#
# getDefaults($$)
# getSysVars()
# checkInputs()
# replaceTokens($)
# checkDir($)
# runJob()
# main()
#
# !PUBLIC DATA MEMBERS:
#
  #============================================================
  # Define global variables (seen in all subroutines below)
  #============================================================
  $CODE_DIRECTORY    = "UNDEFINED";
  $DATE_FILE         = "UNDEFINED";
  $DATE_STRING       = "UNDEFINED";
  $EXECUTABLE        = "UNDEFINED";
  $HOME_DIRECTORY    = "UNDEFINED";
  $JOB_DIRECTORY     = "UNDEFINED";
  $JOB_FILE          = "UNDEFINED";
  $LOG_DIRECTORY     = "UNDEFINED";
  $LOG_ERR           = "UNDEFINED";
  $LOG_FILE          = "UNDEFINED";
  $SUBMIT            = "UNDEFINED";
  $TEMP_DIRECTORY    = "UNDEFINED";
  $USER_ID           = "UNDEFINED";
#
# !CALLING SEQUENCE:
# doGeos5 YYYYMMDD
#
# !REVISION HISTORY: 
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getDefaults
#
# !DESCRIPTION:  Routine getDefaults reads the default values for 
#  input quantities.
#\\
#\\
# !INTERFACE:
#
sub getDefaults($$) {
#
# !INPUT PARAMETERS:
#
  # $fileName : File containing default settings to be read
  # $date     : YYYYMMDD date for which to process met data
  my ( $fileName, $date ) = @_;
#
# !CALLING SEQUENCE:
# &getDefaults( FILENAME, DATE );
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # Local variables
  my $line         = "";   
  my @file         = "";
  my @result       = "";

  #--------------------------------------
  # Read variable settings from the file
  #--------------------------------------

  # Read defaults file into an array (remove newlines)
  open( I, "<$fileName" ) or die "Cannot open $fileName!\n";
  chomp( @file = <I> );
  close( I );

  # Loop thru each line in the file
  for ( my $i = 0; $i <  scalar( @file ); $i++ ) {

    if ( $file[$i] =~ "==> Submit Statement" ) {
      $SUBMIT = $file[++$i];
       
    } elsif ( $file[$i] =~ "==> Code Directory" ) {
      $CODE_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Job Directory" ) {
      $JOB_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Log Directory" ) {
      $LOG_DIRECTORY  = $file[++$i];

    } elsif ( $file[$i] =~ "==> Temporary Directory" ) {
      $TEMP_DIRECTORY = $file[++$i];

    } elsif ( $file[$i] =~ "==> Program Executable" ) {
      $EXECUTABLE = $file[++$i];

    }
  }

  #--------------------------------------
  # Define other variables
  #--------------------------------------

  # Date string
  $DATE_STRING = "$date";

  # File to pass date to F90 code
  $DATE_FILE   = "$TEMP_DIRECTORY/$DATE_STRING.$$";

  # Log error file
  $LOG_ERR     = "$LOG_DIRECTORY/log.doGeos5.error";

  # Log file
  $LOG_FILE    = "$LOG_DIRECTORY/log.doGeos5.{DSTR}.$$";

  # Job script
  $JOB_FILE    = "$JOB_DIRECTORY/job.doGeos5.{DSTR}.$$";  

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getSysVars
#
# !DESCRIPTION: Routine getSysVars returns system variables \$USER and \$HOME.
#\\
#\\
# !INTERFACE:
#
sub getSysVars() {
#
# !CALLING SEQUENCE:
# &getSysVars();
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------
#BOC

  # User ID (remove newline)
  $USER_ID = qx( echo \$USER );
  chomp( $USER_ID );
  
  # Home directory (remove newline)
  $HOME_DIRECTORY = qx( echo \$HOME );
  chomp( $HOME_DIRECTORY );

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkInputs
#
# !DESCRIPTION: Routine checkInputs does the following:
# \begin{enumerate}
# \item Replaces string tokens in variables with replacement text
# \item Checks to see if directories exist
# \end{enumerate}
#
# !INTERFACE:
#
sub checkInputs() {
#
# !CALLING SEQUENCE:
# &checkInputs();
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------
#BOC

  # Replace tokens in variable names
  $CODE_DIRECTORY = &replaceTokens( $CODE_DIRECTORY );
  $EXECUTABLE     = &replaceTokens( $EXECUTABLE     );
  $JOB_DIRECTORY  = &replaceTokens( $JOB_DIRECTORY  );
  $JOB_FILE       = &replaceTokens( $JOB_FILE       );
  $LOG_DIRECTORY  = &replaceTokens( $LOG_DIRECTORY  );
  $LOG_ERR        = &replaceTokens( $LOG_ERR        );
  $LOG_FILE       = &replaceTokens( $LOG_FILE       );
  $SUBMIT         = &replaceTokens( $SUBMIT         );
  $TEMP_DIRECTORY = &replaceTokens( $TEMP_DIRECTORY );

  # Check to make sure directories exist
  &checkDir( $CODE_DIRECTORY );
  &checkDir( $JOB_DIRECTORY  );
  &checkDir( $LOG_DIRECTORY  );
  &checkDir( $TEMP_DIRECTORY );

  # Return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: replaceTokens
#
# !DESCRIPTION: Subroutine replaceTokens replaces tokens in a variable.  
#\\
#\\
# !INTERFACE:
#
sub replaceTokens($) {
#
# !INPUT PARAMETERS:
#
  # $var: Name of the string in which to replace tokens
  my ( $var ) = @_; 
#
# !CALLING SEQUENCE:
#  $var = &replaceTokens( $var );
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------
#BOC

  # Replace tokens in the variable names
  $var =~ s/{DSTR}/$DATE_STRING/g;
  $var =~ s/{HOME}/$HOME_DIRECTORY/g;
  $var =~ s/{JOB}/$JOB_FILE/g;
  $var =~ s/{LOGERR}/$LOG_ERR/g;
  $var =~ s/{USER}/$USER_ID/g;
  $var =~ s/{THREAD}//g;

  # Return to calling program
  return( $var );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkDir
#
# !DESCRIPTION: Subroutine checkDir checks to see if a directory exists.
#\\
#\\
# !INTERFACE:
#
sub checkDir($) {
#
# !INPUT PARAMETERS:
#
  # $dir : Directory to be checked
  my ( $dir ) = @_;
#
# !CALLING SEQUENCE:
#  &checkDir( $dir );
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------
#BOC

  # Stop with error if directory doesn't exist
  if ( !( -d $dir ) ) { 
    print "doGeos5 ERROR: Directory does not exist: $dir\n";
    exit(1)
  }
  
  # Otherwise return normally
  return(0);
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: runJob
#
# !DESCRIPTION: Subroutine runJob creates the job script and executes it.
#\\
#\\
# !INTERFACE:
#
sub runJob() {
#
# !CALLING SEQUENCE:
#  &runJob();
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#  28 Feb 2012 - R. Yantosca - Now force an automount with an ls command
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES
#
  my $fileTypes = "A1";

  #-----------------------------------------
  # Define file with date 
  #-----------------------------------------

  # Save date in a file to pass to the F90 code
  open( O, ">$DATE_FILE" ) or die "Cannot open $DATE_FILE!\n";
  print O "$DATE_STRING\n";
  close( O );

  #-----------------------------------------
  # Define job script in a "here" document
  #-----------------------------------------
  my $txt =<<EOF;
#!/usr/bin/perl -w

# Local variables
my \$sLog  = qq($LOG_FILE);

# Make files world-readable
umask(022);

# Echo starting time
qx( echo "=======================================" >> \$sLog );
qx( echo "doGeos5: Extracting GEOS-5 Met Data!"    >> \$sLog );
qx( echo "Started on `date`"                       >> \$sLog );
qx( echo                                           >> \$sLog );

# List the temp directory first to force a directory mount
qx( ls $TEMP_DIRECTORY > /dev/null );

# Run the GEOS-5 data extraction code
qx( umask 022; cd $CODE_DIRECTORY; $EXECUTABLE < $DATE_FILE >> \$sLog );

# Move files from the temp directory to the data directory
qx( ./moveGeos57 $DATE_STRING $fileTypes >> \$sLog );

# Remove the date file
qx( rm -f $DATE_FILE >> /dev/null ); 

# Echo ending time
qx( echo                      >> \$sLog );
qx( echo "Finished on `date`" >> \$sLog );
qx( echo                      >> \$sLog );

exit(0)
EOF

  # Write job script to a file
  open( O, ">$JOB_FILE" ) or die "Cannot open $JOB_FILE!\n";
  print O "$txt\n";
  close( O );

  # Make run script executable
  chmod( 0755, $JOB_FILE );

  # Submit job to queue system (or run interactively)
  qx( $SUBMIT );

  # Return normally
  return( 0 );
}
#EOC
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: main
#
# !DESCRIPTION: Routine main is the driver routine for the doGeos5 script.
#\\
#\\
# !INTERFACE:
#
sub main() {
#
# !CALLING SEQUENCE:
#  &main();
#
# !REVISION HISTORY:
#  24 Oct 2011 - R. Yantosca - Initial version, based on GEOS_5/perl/doGeos5
#EOP
#------------------------------------------------------------------------------

  # Error check arguments
  if ( scalar( @ARGV ) == 0 ) { 
    print "Usage: doGeos57 YYYYMMDD\n"; 
    exit(1);
  }

  # Get default values
  &getDefaults( "doGeos57.input", $ARGV[0] );

  # Get system variables
  &getSysVars();

  # Replace tokens w/ values and error check directories
  &checkInputs();

  # Write the job file and submit it to the queue
  &runJob();
					
  # Return normally
  return(0);
}
#EOC

#------------------------------------------------------------------------------

# Start main program
main();

# Exit normally
exit(0);
