#!/usr/bin/perl -w

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: purgeGeosFp
#
# !DESCRIPTION: This perl script checks to see if all met fields for a given
#  date have been processed properly.  If so, it will remove the "raw" met
#  data files from the data download directory.  This is more or less 
#  customized for SEAC4RS, in order to let the data download process proceed
#  in a "hands-off" fashion.
#\\
#\\
# !USES:
#
require 5.003;                      # Need this version of Perl or newer
use English;                        # Use English language
use Carp;                           # Get detailed error messages
use strict;                         # IMPLICIT NONE syntax
#
# !PUBLIC DATA MEMBERS:
#

# Raw met field directory
our $RAW_MET_DIR           = "";    # Dir where raw met fields are stored
 
# CH Nested grid met fields
our $NESTED_C_MET_DIR     = "";     # Nested CH  met field directory
our $FILE_NESTED_C_A1     = "";     # Nested CH  GEOS-FP "A1"     file name
our $SIZE_NESTED_C_A1     = "";     # Nested CH  GEOS-FP "A1"     file size
our $FILE_NESTED_C_A3cld  = "";     # Nested CH  GEOS-FP "A3cld"  file name
our $SIZE_NESTED_C_A3cld  = "";     # Nested CH  GEOS-FP "A3cld"  file size
our $FILE_NESTED_C_A3dyn  = "";     # Nested CH  GEOS-FP "A3dyn"  file name
our $SIZE_NESTED_C_A3dyn  = "";     # Nested CH  GEOS-FP "A3dyn"  file size
our $FILE_NESTED_C_A3mstC = "";     # Nested CH  GEOS-FP "A3mstC" file name
our $SIZE_NESTED_C_A3mstC = "";     # Nested CH  GEOS-FP "A3mstC" file size
our $FILE_NESTED_C_A3mstE = "";     # Nested CH  GEOS-FP "A3mstE" file name
our $SIZE_NESTED_C_A3mstE = "";     # Nested CH  GEOS-FP "A3mstE" file size
our $FILE_NESTED_C_I3     = "";     # Nested CH  GEOS-FP "I3"     file name
our $SIZE_NESTED_C_I3     = "";     # Nested CH  GEOS-FP "I3"     file size

# EU Nested grid met fields
our $NESTED_E_MET_DIR     = "";     # Nested EU  met field directory
our $FILE_NESTED_E_A1     = "";     # Nested EU  GEOS-FP "A1"     file name
our $SIZE_NESTED_E_A1     = "";     # Nested EU  GEOS-FP "A1"     file size
our $FILE_NESTED_E_A3cld  = "";     # Nested EU  GEOS-FP "A3cld"  file name
our $SIZE_NESTED_E_A3cld  = "";     # Nested EU  GEOS-FP "A3cld"  file size
our $FILE_NESTED_E_A3dyn  = "";     # Nested EU  GEOS-FP "A3dyn"  file name
our $SIZE_NESTED_E_A3dyn  = "";     # Nested EU  GEOS-FP "A3dyn"  file size
our $FILE_NESTED_E_A3mstC = "";     # Nested EU  GEOS-FP "A3mstC" file name
our $SIZE_NESTED_E_A3mstC = "";     # Nested EU  GEOS-FP "A3mstC" file size
our $FILE_NESTED_E_A3mstE = "";     # Nested EU  GEOS-FP "A3mstE" file name
our $SIZE_NESTED_E_A3mstE = "";     # Nested EU  GEOS-FP "A3mstE" file size
our $FILE_NESTED_E_I3     = "";     # Nested EU  GEOS-FP "I3"     file name
our $SIZE_NESTED_E_I3     = "";     # Nested EU  GEOS-FP "I3"     file size

# NA nested grid met fields
our $NESTED_N_MET_DIR     = "";     # Nested NA   met field directory
our $FILE_NESTED_N_A1     = "";     # Nested NA   GEOS-FP "A1"     file name
our $SIZE_NESTED_N_A1     = "";     # Nested NA   GEOS-FP "A1"     file size
our $FILE_NESTED_N_A3cld  = "";     # Nested NA   GEOS-FP "A3cld"  file name
our $SIZE_NESTED_N_A3cld  = "";     # Nested NA   GEOS-FP "A3cld"  file size
our $FILE_NESTED_N_A3dyn  = "";     # Nested NA   GEOS-FP "A3dyn"  file name
our $SIZE_NESTED_N_A3dyn  = "";     # Nested NA   GEOS-FP "A3dyn"  file size
our $FILE_NESTED_N_A3mstC = "";     # Nested NA   GEOS-FP "A3mstC" file name
our $SIZE_NESTED_N_A3mstC = "";     # Nested NA   GEOS-FP "A3mstC" file size
our $FILE_NESTED_N_A3mstE = "";     # Nested NA   GEOS-FP "A3mstE" file name
our $SIZE_NESTED_N_A3mstE = "";     # Nested NA   GEOS-FP "A3mstE" file size
our $FILE_NESTED_N_I3     = "";     # Nested NA   GEOS-FP "I3"     file name
our $SIZE_NESTED_N_I3     = "";     # Nested NA   GEOS-FP "I3"     file size

# SE Nested grid met fields
our $NESTED_S_MET_DIR     = "";     # Nested SE  met field directory
our $FILE_NESTED_S_A1     = "";     # Nested SE  GEOS-FP "A1"     file name
our $SIZE_NESTED_S_A1     = "";     # Nested SE  GEOS-FP "A1"     file size
our $FILE_NESTED_S_A3cld  = "";     # Nested SE  GEOS-FP "A3cld"  file name
our $SIZE_NESTED_S_A3cld  = "";     # Nested SE  GEOS-FP "A3cld"  file size
our $FILE_NESTED_S_A3dyn  = "";     # Nested SE  GEOS-FP "A3dyn"  file name
our $SIZE_NESTED_S_A3dyn  = "";     # Nested SE  GEOS-FP "A3dyn"  file size
our $FILE_NESTED_S_A3mstC = "";     # Nested SE  GEOS-FP "A3mstC" file name
our $SIZE_NESTED_S_A3mstC = "";     # Nested SE  GEOS-FP "A3mstC" file size
our $FILE_NESTED_S_A3mstE = "";     # Nested SE  GEOS-FP "A3mstE" file name
our $SIZE_NESTED_S_A3mstE = "";     # Nested SE  GEOS-FP "A3mstE" file size
our $FILE_NESTED_S_I3     = "";     # Nested SE  GEOS-FP "I3"     file name
our $SIZE_NESTED_S_I3     = "";     # Nested SE  GEOS-FP "I3"     file size

# Global grid met fields    
our $GLOBAL_4_MET_DIR     = "";     # Global 4x5  met field directory
our $FILE_GLOBAL_4_A1     = "";     # Global 4x5  GEOS-FP "A1"     file name
our $SIZE_GLOBAL_4_A1     = "";     # Global 4x5  GEOS-FP "A1"     file size
our $FILE_GLOBAL_4_A3cld  = "";     # Global 4x5  GEOS-FP "A3cld"  file name
our $SIZE_GLOBAL_4_A3cld  = "";     # Global 4x5  GEOS-FP "A3cld"  file size
our $FILE_GLOBAL_4_A3dyn  = "";     # Global 4x5  GEOS-FP "A3dyn"  file name
our $SIZE_GLOBAL_4_A3dyn  = "";     # Global 4x5  GEOS-FP "A3dyn"  file size
our $FILE_GLOBAL_4_A3mstC = "";     # Global 4x5  GEOS-FP "A3mstC" file name
our $SIZE_GLOBAL_4_A3mstC = "";     # Global 4x5  GEOS-FP "A3mstC" file size
our $FILE_GLOBAL_4_A3mstE = "";     # Global 4x5  GEOS-FP "A3mstE" file name
our $SIZE_GLOBAL_4_A3mstE = "";     # Global 4x5  GEOS-FP "A3mstE" file size
our $FILE_GLOBAL_4_I3     = "";     # Global 4x5  GEOS-FP "I3"     file name
our $SIZE_GLOBAL_4_I3     = "";     # Global 4x5  GEOS-FP "I3"     file size
				    
# Global grid met fields    	    
our $GLOBAL_2_MET_DIR     = "";     # Global 2x25 met field directory
our $FILE_GLOBAL_2_A1     = "";     # Global 2x25 GEOS-FP "A1"     file name
our $SIZE_GLOBAL_2_A1     = "";     # Global 2x25 GEOS-FP "A1"     file size
our $FILE_GLOBAL_2_A3cld  = "";     # Global 2x25 GEOS-FP "A3cld"  file name
our $SIZE_GLOBAL_2_A3cld  = "";     # Global 2x25 GEOS-FP "A3cld"  file size
our $FILE_GLOBAL_2_A3dyn  = "";     # Global 2x25 GEOS-FP "A3dyn"  file name
our $SIZE_GLOBAL_2_A3dyn  = "";     # Global 2x25 GEOS-FP "A3dyn"  file size
our $FILE_GLOBAL_2_A3mstC = "";     # Global 2x25 GEOS-FP "A3mstC" file name
our $SIZE_GLOBAL_2_A3mstC = "";     # Global 2x25 GEOS-FP "A3mstC" file size
our $FILE_GLOBAL_2_A3mstE = "";     # Global 2x25 GEOS-FP "A3mstE" file name
our $SIZE_GLOBAL_2_A3mstE = "";     # Global 2x25 GEOS-FP "A3mstE" file size
our $FILE_GLOBAL_2_I3     = "";     # Global 2x25 GEOS-FP "I3"     file name
our $SIZE_GLOBAL_2_I3     = "";     # Global 2x25 GEOS-FP "I3"     file size
#  
# !PUBLIC MEMBER FUNCTIONS:
#  &main()
#
# !PRIVATE MEMBER FUNCTIONS:
#  &getDefaults : Reads default values
#  &checkNested : Checks to see if all files are present for nested simulation 
#  &replaceDate : Replaces YYYY, MM, DD in a string with date values
#
# !CALLING SEQUENCE:
#  sleepNrt YYYYMMDD
#
# !REMARKS:
#  (1) Reads default values from input file "doGeos57.input".
#  (2) This is more or less a kludge for SEAC4RS.  This will allow the
#      met field scripts to operate in a more or less "hands-off" manner.
#
# !REVISION HISTORY: 
#  08 Aug 2013 - R. Yantosca - Initial version, based on sleepNRT (SEAC4RS)
#  25 Sep 2013 - R. Yantosca - Renamed global vars for CH, NA, 4x5, 2x25
#  11 Feb 2014 - R. Yantosca - Added global vars for EU and SE nested grids
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getDefaults
#
# !DESCRIPTION: Routine getDefaults reads default values (such as directory
#  paths, file names, file sizes, etc) from the "doNrt.input" file.  This 
#  allows you to be able to change directories, file names, etc. without 
#  having to rewrite scripts.
#\\
#\\
# !INTERFACE:
#
sub getDefaults($) {
#
# !INPUT PARAMETERS:
#
  my ( $fileName ) = @_;  # File in which NRT defaults are stored
#
# !CALLING SEQUENCE:
#  ( $logDir, $webDir ) = &getDefaults( $fileName );
#
# !REVISION HISTORY:
#  22 May 2013 - R. Yantosca - Based on "sleepNrt" from NRT-ARCTAS
#  29 Jul 2013 - R. Yantosca - Fixed typo in perl script directory heading
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my $line   = "";
  my @f      = "";
  my @result = "";

  # Read defaults file into an array (remove newlines)
  open( I, "<$fileName" ) or die "Cannot open $fileName!\n";
  chomp( @f = <I> );
  close( I );

  # Loop thru each line in the file; parse information into global variables
  for ( my $i = 0; $i < scalar( @f ); $i++ ) {

    if ( $f[$i] =~ "==> Raw Met Data Directory" ) {
      $RAW_MET_DIR = $f[++$i];

    } elsif ( $f[$i] =~ "==> CH Nested" ) {
      $NESTED_C_MET_DIR                                =           $f[++$i] ;
      ( $SIZE_NESTED_C_A1,     $FILE_NESTED_C_A1     ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_C_A3cld,  $FILE_NESTED_C_A3cld  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_C_A3dyn,  $FILE_NESTED_C_A3dyn  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_C_A3mstC, $FILE_NESTED_C_A3mstC ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_C_A3mstE, $FILE_NESTED_C_A3mstE ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_C_I3,     $FILE_NESTED_C_I3     ) = split(' ',$f[++$i]);

    } elsif ( $f[$i] =~ "==> EU Nested" ) {
      $NESTED_E_MET_DIR                                =           $f[++$i] ;
      ( $SIZE_NESTED_E_A1,     $FILE_NESTED_E_A1     ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_E_A3cld,  $FILE_NESTED_E_A3cld  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_E_A3dyn,  $FILE_NESTED_E_A3dyn  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_E_A3mstC, $FILE_NESTED_E_A3mstC ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_E_A3mstE, $FILE_NESTED_E_A3mstE ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_E_I3,     $FILE_NESTED_E_I3     ) = split(' ',$f[++$i]);

    } elsif ( $f[$i] =~ "==> NA Nested" ) {
      $NESTED_N_MET_DIR                                =           $f[++$i] ;
      ( $SIZE_NESTED_N_A1,     $FILE_NESTED_N_A1     ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_N_A3cld,  $FILE_NESTED_N_A3cld  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_N_A3dyn,  $FILE_NESTED_N_A3dyn  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_N_A3mstC, $FILE_NESTED_N_A3mstC ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_N_A3mstE, $FILE_NESTED_N_A3mstE ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_N_I3,     $FILE_NESTED_N_I3     ) = split(' ',$f[++$i]);

    } elsif ( $f[$i] =~ "==> SE Nested" ) {
      $NESTED_S_MET_DIR                                =           $f[++$i] ;
      ( $SIZE_NESTED_S_A1,     $FILE_NESTED_S_A1     ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_S_A3cld,  $FILE_NESTED_S_A3cld  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_S_A3dyn,  $FILE_NESTED_S_A3dyn  ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_S_A3mstC, $FILE_NESTED_S_A3mstC ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_S_A3mstE, $FILE_NESTED_S_A3mstE ) = split(' ',$f[++$i]);
      ( $SIZE_NESTED_S_I3,     $FILE_NESTED_S_I3     ) = split(' ',$f[++$i]);

    } elsif ( $f[$i] =~ "==> 4x5 Global" ) {
      $GLOBAL_4_MET_DIR                                =           $f[++$i] ;
      ( $SIZE_GLOBAL_4_A1,     $FILE_GLOBAL_4_A1     ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_4_A3cld,  $FILE_GLOBAL_4_A3cld  ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_4_A3dyn,  $FILE_GLOBAL_4_A3dyn  ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_4_A3mstC, $FILE_GLOBAL_4_A3mstC ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_4_A3mstE, $FILE_GLOBAL_4_A3mstE ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_4_I3,     $FILE_GLOBAL_4_I3     ) = split(' ',$f[++$i]);
 
    } elsif ( $f[$i] =~ "==> 2x25 Global" ) {
      $GLOBAL_2_MET_DIR                                =           $f[++$i] ;
      ( $SIZE_GLOBAL_2_A1,     $FILE_GLOBAL_2_A1     ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_2_A3cld,  $FILE_GLOBAL_2_A3cld  ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_2_A3dyn,  $FILE_GLOBAL_2_A3dyn  ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_2_A3mstC, $FILE_GLOBAL_2_A3mstC ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_2_A3mstE, $FILE_GLOBAL_2_A3mstE ) = split(' ',$f[++$i]);
      ( $SIZE_GLOBAL_2_I3,     $FILE_GLOBAL_2_I3     ) = split(' ',$f[++$i])
   
    }
  }

  # Return normally
  return( $? );
}
#
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: uniq
#
# !DESCRIPTION: Returns the unique values in an array (analogous to the
#  UNIQ function in IDL.
#\\
#\\
# !INTERFACE:
#
sub uniq(@) {
#
# !INPUT PARAMETERS:
#
  my ( @array ) = @_;   # Input array to be parsed
#
# !RETURN VALUE:
#
  my $unique = ();      # Retursn unique values in @array
#
# !CALLING SEQUENCE:
#  $unique = &uniq( @array );
#
# !REMARKS:
#  Algorithm from this Internet thread: 
#     http://stackoverflow.com/questions/439647/
#     how-do-i-print-unique-elements-in-perl-array
#
# !REVISION HISTORY:
#  08 Aug 2013 - R. Yantosca - Initial version,
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#

  # Create a hash
  my %seen;

  # Populate the hash with only unique values, save into an array
  my @unique = grep { ! $seen{$_}++ } @array;

  # Return the value of unique arrays
  return( @unique );
}
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: replaceDate
#
# !DESCRIPTION: Routine replaceDate replaces date tokens (YYYY, MM, DD) in
#  a string with the actual year, month, and date values.
#\\
#\\
# !INTERFACE:
#
sub replaceDate($$) {
#
# !INPUT PARAMETERS:
#
  my ( $str, $date ) = @_;  # $str: String w/ tokens; 
                            # $date: YYYYMMDD date
#
# !RETURN VALUE:
#
  my $newStr = "";          # Updated string 
#
# !CALLING SEQUENCE:
#  $newStr = &replaceDate( "file.YYYYMMDD", 20130101 );
#
# !REVISION HISTORY:
#  08 Aug 2013 - R. Yantosca - Initial version, based on NrtUtils.PM (SEAC4RS)
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  my $yyyy = substr( $date, 0, 4 );    # Extract year  from $date
  my $mm   = substr( $date, 4, 2 );    # Extract month from $date
  my $dd   = substr( $date, 6, 2 );    # Extract day   from $date

  # Replace tokens
  $newStr =  $str;          
  $newStr =~ s/YYYY/$yyyy/g;           # Replace year 
  $newStr =~ s/MM/$mm/g;               # Replace month
  $newStr =~ s/DD/$dd/g;               # Replace day

  # Return modified string
  return( $newStr );
}
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: getRawMetFieldDates
#
# !DESCRIPTION: Routine getRawMetFieldDates finds a list of dates corresponding
#  to the files that are currently sitting in the raw met field directory.
#\\
#\\
# !INTERFACE:
#
sub getRawMetFieldDates() {
#
# !RETURN VALUE:
#
  my @dates = ();   # Dates of files in the r
#
# !CALLING SEQUENCE:
#  @dates = &checkRawMetFiles();
#
# !REVISION HISTORY:
#  08 Aug 2013 - R. Yantosca - Initial version, based on "sleepNrt" (SEAC4RS)
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # Scalars
  my $cmd       = "";
  my $file      = "";
  
  # Arrays
  my @files     = ();
  my @subString = ();

  # Get the list of files in the data download directory
  $cmd = "ls -1 $RAW_MET_DIR/*GEOS.fp*";
  chomp( @files = qx( $cmd ) );

  # Find the date corresponding to each raw met field file
  foreach $file ( @files ) {
    @subString = split( '\.', $file );   
    @dates     = ( @dates, substr( $subString[4], 0, 8 ) );
  }

  # Then take only the unique values
  @dates = uniq( @dates );

  # Return to calling routine
  return( @dates );
}
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: processedMetExists
#
# !DESCRIPTION: Routine processedMetExists makes sure that all met field and restart
#  files are present before the SEAC4RS GLOBAL AND NESTED GRID SIMULATIONS 
#  are started.
#\\
#\\
# !INTERFACE:
#
sub processedMetExists($) {
#
# !INPUT PARAMETERS:
#
  my ( $date ) = @_;     # Today's date in YYYYMMDD format
#
# !RETURN VALUE:
#
  my $rc         = 0;       # Will return 0 if successful
#
# !CALLING SEQUENCE:
#  &checkFiles( YYYYMMDD )
#
# !REVISION HISTORY:
#  08 Aug 2013 - R. Yantosca - Initial version, based on "sleepNrt" (SEAC4RS)
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # For CH nested grid
  my $ch_a1     = "$NESTED_C_MET_DIR/$FILE_NESTED_C_A1";     # A1     met
  my $ch_a3Cld  = "$NESTED_C_MET_DIR/$FILE_NESTED_C_A3cld";  # A3cld  met
  my $ch_a3Dyn  = "$NESTED_C_MET_DIR/$FILE_NESTED_C_A3dyn";  # A3dyn  met
  my $ch_a3MstC = "$NESTED_C_MET_DIR/$FILE_NESTED_C_A3mstC"; # A3mstC met
  my $ch_a3MstE = "$NESTED_C_MET_DIR/$FILE_NESTED_C_A3mstE"; # A3mstE met
  my $ch_i3     = "$NESTED_C_MET_DIR/$FILE_NESTED_C_I3";     # I3     met
 
  # For EU nested grid
  my $eu_a1     = "$NESTED_E_MET_DIR/$FILE_NESTED_E_A1";     # A1     met
  my $eu_a3Cld  = "$NESTED_E_MET_DIR/$FILE_NESTED_E_A3cld";  # A3cld  met
  my $eu_a3Dyn  = "$NESTED_E_MET_DIR/$FILE_NESTED_E_A3dyn";  # A3dyn  met
  my $eu_a3MstC = "$NESTED_E_MET_DIR/$FILE_NESTED_E_A3mstC"; # A3mstC met
  my $eu_a3MstE = "$NESTED_E_MET_DIR/$FILE_NESTED_E_A3mstE"; # A3mstE met
  my $eu_i3     = "$NESTED_E_MET_DIR/$FILE_NESTED_E_I3";     # I3     met

  # For NA nested grid
  my $na_a1     = "$NESTED_N_MET_DIR/$FILE_NESTED_N_A1";     # A1     met
  my $na_a3Cld  = "$NESTED_N_MET_DIR/$FILE_NESTED_N_A3cld";  # A3cld  met
  my $na_a3Dyn  = "$NESTED_N_MET_DIR/$FILE_NESTED_N_A3dyn";  # A3dyn  met
  my $na_a3MstC = "$NESTED_N_MET_DIR/$FILE_NESTED_N_A3mstC"; # A3mstC met
  my $na_a3MstE = "$NESTED_N_MET_DIR/$FILE_NESTED_N_A3mstE"; # A3mstE met
  my $na_i3     = "$NESTED_N_MET_DIR/$FILE_NESTED_N_I3";     # I3     met

  # For SE nested grid
  my $se_a1     = "$NESTED_S_MET_DIR/$FILE_NESTED_S_A1";     # A1     met
  my $se_a3Cld  = "$NESTED_S_MET_DIR/$FILE_NESTED_S_A3cld";  # A3cld  met
  my $se_a3Dyn  = "$NESTED_S_MET_DIR/$FILE_NESTED_S_A3dyn";  # A3dyn  met
  my $se_a3MstC = "$NESTED_S_MET_DIR/$FILE_NESTED_S_A3mstC"; # A3mstC met
  my $se_a3MstE = "$NESTED_S_MET_DIR/$FILE_NESTED_S_A3mstE"; # A3mstE met
  my $se_i3     = "$NESTED_S_MET_DIR/$FILE_NESTED_S_I3";     # I3     met

  # For 2x25 global grid
  my $g2_a1     = "$GLOBAL_2_MET_DIR/$FILE_GLOBAL_2_A1";     # A1     met
  my $g2_a3Cld  = "$GLOBAL_2_MET_DIR/$FILE_GLOBAL_2_A3cld";  # A3cld  met
  my $g2_a3Dyn  = "$GLOBAL_2_MET_DIR/$FILE_GLOBAL_2_A3dyn";  # A3dyn  met
  my $g2_a3MstC = "$GLOBAL_2_MET_DIR/$FILE_GLOBAL_2_A3mstC"; # A3mstC met
  my $g2_a3MstE = "$GLOBAL_2_MET_DIR/$FILE_GLOBAL_2_A3mstE"; # A3mstE met
  my $g2_i3     = "$GLOBAL_2_MET_DIR/$FILE_GLOBAL_2_I3";     # I3     met

  # For 4x5 global grid
  my $g4_a1     = "$GLOBAL_4_MET_DIR/$FILE_GLOBAL_4_A1";     # A1     met
  my $g4_a3Cld  = "$GLOBAL_4_MET_DIR/$FILE_GLOBAL_4_A3cld";  # A3cld  met
  my $g4_a3Dyn  = "$GLOBAL_4_MET_DIR/$FILE_GLOBAL_4_A3dyn";  # A3dyn  met
  my $g4_a3MstC = "$GLOBAL_4_MET_DIR/$FILE_GLOBAL_4_A3mstC"; # A3mstC met
  my $g4_a3MstE = "$GLOBAL_4_MET_DIR/$FILE_GLOBAL_4_A3mstE"; # A3mstE met
  my $g4_i3     = "$GLOBAL_4_MET_DIR/$FILE_GLOBAL_4_I3";     # I3     met

  #========================================================================
  # Replace tokens in file names & directory paths
  #========================================================================

  $ch_a1     = &replaceDate( $ch_a1,     $date );
  $ch_a3Cld  = &replaceDate( $ch_a3Cld,  $date );
  $ch_a3Dyn  = &replaceDate( $ch_a3Dyn,  $date );
  $ch_a3MstC = &replaceDate( $ch_a3MstC, $date );
  $ch_a3MstE = &replaceDate( $ch_a3MstE, $date );
  $ch_i3     = &replaceDate( $ch_i3,     $date );

  $eu_a1     = &replaceDate( $eu_a1,     $date );
  $eu_a3Cld  = &replaceDate( $eu_a3Cld,  $date );
  $eu_a3Dyn  = &replaceDate( $eu_a3Dyn,  $date );
  $eu_a3MstC = &replaceDate( $eu_a3MstC, $date );
  $eu_a3MstE = &replaceDate( $eu_a3MstE, $date );
  $eu_i3     = &replaceDate( $eu_i3,     $date );

  $na_a1     = &replaceDate( $na_a1,     $date );
  $na_a3Cld  = &replaceDate( $na_a3Cld,  $date );
  $na_a3Dyn  = &replaceDate( $na_a3Dyn,  $date );
  $na_a3MstC = &replaceDate( $na_a3MstC, $date );
  $na_a3MstE = &replaceDate( $na_a3MstE, $date );
  $na_i3     = &replaceDate( $na_i3,     $date );

  $se_a1     = &replaceDate( $se_a1,     $date );
  $se_a3Cld  = &replaceDate( $se_a3Cld,  $date );
  $se_a3Dyn  = &replaceDate( $se_a3Dyn,  $date );
  $se_a3MstC = &replaceDate( $se_a3MstC, $date );
  $se_a3MstE = &replaceDate( $se_a3MstE, $date );
  $se_i3     = &replaceDate( $se_i3,     $date );

  $g2_a1     = &replaceDate( $g2_a1,     $date );
  $g2_a3Cld  = &replaceDate( $g2_a3Cld,  $date );
  $g2_a3Dyn  = &replaceDate( $g2_a3Dyn,  $date );
  $g2_a3MstC = &replaceDate( $g2_a3MstC, $date );
  $g2_a3MstE = &replaceDate( $g2_a3MstE, $date );
  $g2_i3     = &replaceDate( $g2_i3,     $date );

  $g4_a1     = &replaceDate( $g4_a1,     $date );
  $g4_a3Cld  = &replaceDate( $g4_a3Cld,  $date );
  $g4_a3Dyn  = &replaceDate( $g4_a3Dyn,  $date );
  $g4_a3MstC = &replaceDate( $g4_a3MstC, $date );
  $g4_a3MstE = &replaceDate( $g4_a3MstE, $date );
  $g4_i3     = &replaceDate( $g4_i3,     $date );

  #========================================================================
  # Check if processed met field files are fully-sized
  #========================================================================

  # CH nested grid met files
  if ( -f $ch_a1     ) { $rc += ( -s $ch_a1     eq $SIZE_NESTED_C_A1     ); }
  if ( -f $ch_a3Cld  ) { $rc += ( -s $ch_a3Cld  eq $SIZE_NESTED_C_A3cld  ); }
  if ( -f $ch_a3Dyn  ) { $rc += ( -s $ch_a3Dyn  eq $SIZE_NESTED_C_A3dyn  ); }
  if ( -f $ch_a3MstC ) { $rc += ( -s $ch_a3MstC eq $SIZE_NESTED_C_A3mstC ); }
  if ( -f $ch_a3MstE ) { $rc += ( -s $ch_a3MstE eq $SIZE_NESTED_C_A3mstE ); }
  if ( -f $ch_i3     ) { $rc += ( -s $ch_i3     eq $SIZE_NESTED_C_I3     ); }

  # EU nested grid met files
  if ( -f $eu_a1     ) { $rc += ( -s $eu_a1     eq $SIZE_NESTED_E_A1     ); }
  if ( -f $eu_a3Cld  ) { $rc += ( -s $eu_a3Cld  eq $SIZE_NESTED_E_A3cld  ); }
  if ( -f $eu_a3Dyn  ) { $rc += ( -s $eu_a3Dyn  eq $SIZE_NESTED_E_A3dyn  ); }
  if ( -f $eu_a3MstC ) { $rc += ( -s $eu_a3MstC eq $SIZE_NESTED_E_A3mstC ); }
  if ( -f $eu_a3MstE ) { $rc += ( -s $eu_a3MstE eq $SIZE_NESTED_E_A3mstE ); }
  if ( -f $eu_i3     ) { $rc += ( -s $eu_i3     eq $SIZE_NESTED_E_I3     ); }

  # NA nested grid met files
  if ( -f $na_a1     ) { $rc += ( -s $na_a1     eq $SIZE_NESTED_N_A1     ); }
  if ( -f $na_a3Cld  ) { $rc += ( -s $na_a3Cld  eq $SIZE_NESTED_N_A3cld  ); }
  if ( -f $na_a3Dyn  ) { $rc += ( -s $na_a3Dyn  eq $SIZE_NESTED_N_A3dyn  ); }
  if ( -f $na_a3MstC ) { $rc += ( -s $na_a3MstC eq $SIZE_NESTED_N_A3mstC ); }
  if ( -f $na_a3MstE ) { $rc += ( -s $na_a3MstE eq $SIZE_NESTED_N_A3mstE ); }
  if ( -f $na_i3     ) { $rc += ( -s $na_i3     eq $SIZE_NESTED_N_I3     ); }

  # SE nested grid met files
  if ( -f $se_a1     ) { $rc += ( -s $se_a1     eq $SIZE_NESTED_S_A1     ); }
  if ( -f $se_a3Cld  ) { $rc += ( -s $se_a3Cld  eq $SIZE_NESTED_S_A3cld  ); }
  if ( -f $se_a3Dyn  ) { $rc += ( -s $se_a3Dyn  eq $SIZE_NESTED_S_A3dyn  ); }
  if ( -f $se_a3MstC ) { $rc += ( -s $se_a3MstC eq $SIZE_NESTED_S_A3mstC ); }
  if ( -f $se_a3MstE ) { $rc += ( -s $se_a3MstE eq $SIZE_NESTED_S_A3mstE ); }
  if ( -f $se_i3     ) { $rc += ( -s $se_i3     eq $SIZE_NESTED_S_I3     ); }

  # Global 2 x 2.5 met files
  if ( -f $g2_a1     ) { $rc += ( -s $g2_a1     eq $SIZE_GLOBAL_2_A1     ); }
  if ( -f $g2_a3Cld  ) { $rc += ( -s $g2_a3Cld  eq $SIZE_GLOBAL_2_A3cld  ); }
  if ( -f $g2_a3Dyn  ) { $rc += ( -s $g2_a3Dyn  eq $SIZE_GLOBAL_2_A3dyn  ); }
  if ( -f $g2_a3MstC ) { $rc += ( -s $g2_a3MstC eq $SIZE_GLOBAL_2_A3mstC ); }
  if ( -f $g2_a3MstE ) { $rc += ( -s $g2_a3MstE eq $SIZE_GLOBAL_2_A3mstE ); }
  if ( -f $g2_i3     ) { $rc += ( -s $g2_i3     eq $SIZE_GLOBAL_2_I3     ); }

  # Global 4 x 5 met files
  if ( -f $g4_a1     ) { $rc += ( -s $g4_a1     eq $SIZE_GLOBAL_4_A1     ); }
  if ( -f $g4_a3Cld  ) { $rc += ( -s $g4_a3Cld  eq $SIZE_GLOBAL_4_A3cld  ); }
  if ( -f $g4_a3Dyn  ) { $rc += ( -s $g4_a3Dyn  eq $SIZE_GLOBAL_4_A3dyn  ); }
  if ( -f $g4_a3MstC ) { $rc += ( -s $g4_a3MstC eq $SIZE_GLOBAL_4_A3mstC ); }
  if ( -f $g4_a3MstE ) { $rc += ( -s $g4_a3MstE eq $SIZE_GLOBAL_4_A3mstE ); }
  if ( -f $g4_i3     ) { $rc += ( -s $g4_i3     eq $SIZE_GLOBAL_4_I3     ); }

  # Return success or failure
  return( $rc );
}
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: checkRawMetFiles
#
# !DESCRIPTION: Routine checkNested makes sure that all met field and restart
#  files are present before the SEAC4RS GLOBAL AND NESTED GRID SIMULATIONS 
#  are started.
#\\
#\\
# !INTERFACE:
#
sub purgeRawMetFiles($) {
#
# !INPUT PARAMETERS:
#
  my ( $date ) = @_;     # Today's date in YYYYMMDD format
#
# !RETURN VALUE:
#
  my $rc         = 0;       # Will return 0 if successful
#
# !CALLING SEQUENCE:
#  &checkFiles( YYYYMMDD )
#
# !REVISION HISTORY:
#  08 Aug 2013 - R. Yantosca - Initial version, based on "sleepNrt" (SEAC4RS)
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # For global grid
  my $cmd    = "rm $RAW_MET_DIR/*$date*\n";
  my $result = "";

  # Print ht
  print "$cmd\n";
  chomp( $result = qx( $cmd ) );
  print "$result\n";

  # Print the 
  return( $? );
}
#EOP
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: main
#
# !DESCRIPTION: Routine "main" is the driver program for this script.
#\\
#\\
# !INTERFACE:
#
sub main() {
#
# !CALLING SEQUENCE:
#  sleepNrt YYYYMMDD
#
# !REVISION HISTORY:
#  23 May 2013 - R. Yantosca - Initial version, based on NRT-ARCTAS
#EOP
#------------------------------------------------------------------------------
#BOC
#
# !LOCAL VARIABLES:
#
  # Scalars
  my $date       = "";
  my $errMsg     = "Usage: purgeGeosFp YYYYMMDD\n";
  my $todaysDate = "";

  # Arrays
  my @dates      = ();

  # Make sure we have the proper # of arguments
  if ( scalar( @ARGV ) == 1 ) { $todaysDate = $ARGV[0];     } 
  else                        { print "$errMsg\n"; exit(1); }

  # Read defaults from the input file
  if ( &getDefaults( "doGeosFp.input" ) ) {
    print "ERROR: Could not read 'doGeosFp.input' file!\n";
    exit(2);
  }  

  # Find the dates of raw met field files in the download directory
  @dates =  &getRawMetFieldDates();
  print "purgeGeosFp: Test if we need to delete met fields for dates @dates!\n";

  # Loop over each date in the list
  foreach $date ( @dates ) {

    # Test if any of the files in the met field directory 
    # are for today's date
    if ( $date == $todaysDate ) {

      # As a safety feature, we will not delete met data for today's date
      # in the event that we have to restart a met field processing job
      print "purgeGeosFp: We will not delete met files for today's date: $date\n";
      
    } else {

      # For all other dates, check if the met files have been
      # created properly and are of the expeced file size
      if ( &processedMetExists( $date ) == 12 ) { 

        # If so, then delete the raw data files for those dates
        # so that we do not run out of space in the download directory
        print "purgeGeosFp: Removing raw met files for $date\n";
        &purgeRawMetFiles( $date );
      } 
    }
  }

  # Return the error status code
  return( $? );
}
#EOC

# Call main program
main();

# Exit and pass status code back to Unix shell
exit( $? );


