#!/bin/tcsh -f

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !IROUTINE: runMet
#
# !DESCRIPTION: Subroutine runMet runs the executable files Geos57Driver.0,
#  thru Geos57Driver5 simultaneously.  It takes as input 6 
#\\
#\\
# !INTERFACE:
#
# !CALLING SEQUENCE:
#  runMet script1 script2 script3 script4 script5 script6
#
# !REVISION HISTORY:
#  20 Jan 2012 - R. Yantosca - Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

$1 &   # CN and A1 
$2 &   # A3cld
$3 &   # A3dyn
$4 &   # A3mstC
$5 &   # A3mstE
$6 &   # I3

exit(0);
#EOC
